# Generated by Django 4.2.2 on 2023-06-28 16:40

from django.db import migrations, models
import utils.func_utils
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="product ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="add title for article",
                        max_length=255,
                        verbose_name="title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255, unique=True, verbose_name="product link"
                    ),
                ),
                ("body", models.TextField(verbose_name="contenu")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.func_utils.save_post_cover_file,
                        verbose_name="product cover",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(auto_now=True, verbose_name="date modified"),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
            ],
            options={
                "verbose_name_plural": "blog",
                "ordering": ["-created_at"],
                "get_latest_by": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["id", "uuid"], name="product_pro_id_7edd40_idx"
                    )
                ],
            },
        ),
    ]
