# Generated by Django 4.2.2 on 2023-06-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "get_latest_by": ["-created_at"],
                "ordering": ["-created_at"],
                "verbose_name_plural": "Produit",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
