# Generated by Django 3.2 on 2021-04-15 20:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutus_content', tinymce.models.HTMLField(help_text="Description de l'Entreprise: Activité, Mission, Objectif, etc", verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'qui sommes-nous',
                'db_table': 'aboutus_db',
            },
        ),
        migrations.CreateModel(
            name='PageCGU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgu_content', tinymce.models.HTMLField(help_text="Description de la Condition Générale d'Utilisation du site.", verbose_name='description de la CGU')),
            ],
            options={
                'verbose_name_plural': 'CGU',
                'db_table': 'cgu_db',
            },
        ),
    ]
