# Generated by Django 3.2 on 2021-05-03 21:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text="Description de l'Entreprise: Activité, Mission, Objectif, etc", verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'About Us',
                'db_table': 'aboutus_db',
            },
        ),
        migrations.CreateModel(
            name='PageCGU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text="Description de la Condition Générale d'Utilisation du site.", verbose_name='description de la CGU')),
            ],
            options={
                'verbose_name_plural': 'CGU',
                'db_table': 'cgu_db',
            },
        ),
        migrations.CreateModel(
            name='PageSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Description des questions', verbose_name='description support')),
            ],
            options={
                'verbose_name_plural': 'Support',
                'db_table': 'support_db',
            },
        ),
    ]
