# Generated by Django 3.2 on 2021-04-15 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='aboutus_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='pagecgu',
            old_name='cgu_content',
            new_name='content',
        ),
    ]
