# Generated by Django 3.2.7 on 2021-09-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='email')),
                ('date_joinded', models.DateField(auto_now_add=True, verbose_name='date joined')),
            ],
            options={
                'verbose_name_plural': 'Newsletters',
                'db_table': 'newsletters_db',
                'ordering': ['-date_joinded'],
            },
        ),
        migrations.AddIndex(
            model_name='newsletters',
            index=models.Index(fields=['id'], name='id_index_newsletter'),
        ),
    ]
