# Generated by Django 3.2.7 on 2021-09-29 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_id'),
        ('pages', '0002_auto_20210929_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletters',
            name='post',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.PROTECT, to='blog.post', verbose_name='post'),
            preserve_default=False,
        ),
    ]
