# Generated by Django 3.2 on 2021-04-15 21:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210415_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(help_text='Description des questions', verbose_name='description faq')),
            ],
            options={
                'verbose_name_plural': 'Support',
                'db_table': 'support_db',
            },
        ),
    ]
