# Generated by Django 3.2.7 on 2021-09-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('STUDENT', 'Élève'), ('PARENT_OR_TUTOR', 'Parent/Tuteur'), ('TEACHER', 'Enseignant(e)/Professionnel(le)')], default='STUDENT', max_length=50, verbose_name='user type'),
        ),
    ]
