# Generated by Django 3.2 on 2021-04-24 11:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'get_latest_by': ('-date_joined', '-last_login'), 'ordering': ('-date_joined', '-last_login'), 'verbose_name_plural': 'Etudiant'},
        ),
        migrations.AlterModelOptions(
            name='studentmore',
            options={'verbose_name_plural': 'Etudiant detail'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'get_latest_by': ('-date_joined', '-last_login'), 'ordering': ('-date_joined', '-last_login'), 'verbose_name_plural': 'Intructeur'},
        ),
        migrations.AlterModelOptions(
            name='teachermore',
            options={'verbose_name_plural': 'Etudiant detail'},
        ),
        migrations.RemoveField(
            model_name='studentmore',
            name='make',
        ),
        migrations.RemoveField(
            model_name='studentmore',
            name='model',
        ),
        migrations.RemoveField(
            model_name='studentmore',
            name='year',
        ),
        migrations.RemoveField(
            model_name='teachermore',
            name='gadgets',
        ),
        migrations.AddField(
            model_name='teachermore',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='photo de profile'),
        ),
        migrations.AddField(
            model_name='teachermore',
            name='brief_desc',
            field=models.TextField(blank=True, null=True, verbose_name='brief description'),
        ),
        migrations.AddField(
            model_name='teachermore',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2, verbose_name='pays de résidence'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachermore',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='téléphone'),
        ),
        migrations.AddField(
            model_name='teachermore',
            name='qualification',
            field=models.TextField(blank=True, null=True, verbose_name='qualification'),
        ),
        migrations.AddField(
            model_name='teachermore',
            name='state',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='ville de résidence'),
        ),
        migrations.AlterField(
            model_name='studentmore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='etudiant'),
        ),
        migrations.AlterField(
            model_name='teachermore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher', verbose_name='instructeur'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(django.db.models.functions.text.Lower('first_name'), django.db.models.expressions.OrderBy(django.db.models.functions.text.Upper('last_name'), descending=True), name='first_last_name_idx'),
        ),
    ]
