# Generated by Django 3.2 on 2021-04-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210424_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermore',
            name='facebook',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='teachermore',
            name='linkedin',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='teachermore',
            name='twitter',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
