# Generated by Django 3.2 on 2021-04-26 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210424_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachermore',
            options={'verbose_name_plural': 'Intructeur detail'},
        ),
    ]
