# Generated by Django 3.2 on 2021-04-26 21:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_teachermore_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermore',
            name='brief_desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='brief description'),
        ),
        migrations.AlterField(
            model_name='teachermore',
            name='qualification',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='qualification'),
        ),
    ]
