# Generated by Django 3.2.6 on 2021-09-25 11:46

from django.db import migrations, models
import utils.func_utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='meta_description',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.func_utils.save_post_cover_file, verbose_name='post cover'),
        ),
    ]
