# Generated by Django 3.2.6 on 2021-09-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210925_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='add title for article', max_length=255, verbose_name='title'),
        ),
    ]
