# Generated by Django 3.2.7 on 2021-09-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['-date_created'], 'ordering': ['-date_created'], 'verbose_name_plural': 'blog'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish_date',
        ),
    ]
