# Generated by Django 3.2.7 on 2021-09-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210926_0314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['-created_at'], 'ordering': ['-created_at'], 'verbose_name_plural': 'blog'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
