# Generated by Django 3.2.7 on 2021-12-24 19:42

from django.db import migrations, models
import django.db.models.deletion
import utils.func_utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Cours ID')),
                ('order', utils.func_utils.CustomFields(blank=True, verbose_name='chapiter number')),
                ('title', models.CharField(help_text='Rédigez un titre de cours de 60 caractères.', max_length=60, verbose_name='chapter title')),
                ('description', models.TextField(blank=True, help_text='chapiter description', max_length=180, null=True, verbose_name='chapiter description')),
                ('slug', models.SlugField(blank=True, help_text='link this chapiter', unique=True, verbose_name='link this chapiter')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='date created of courses')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='date updated of courses')),
            ],
            options={
                'verbose_name_plural': 'courses',
                'ordering': ['order'],
                'get_latest_by': ['created_at', 'update_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Subject ID')),
                ('title', models.CharField(help_text='ajouter un titre de 60 caractères.', max_length=60, verbose_name='Subject title')),
                ('subtitle', models.CharField(blank=True, help_text='ajouter un sous-titre de 200 caractères.', max_length=200, null=True, verbose_name='Subject sub-title')),
                ('price', models.PositiveIntegerField(default=1500, help_text='add course price', verbose_name='course price')),
                ('sale_price', models.PositiveIntegerField(blank=True, default=0, help_text='add course sale price', null=True, verbose_name='course sale price')),
                ('language', models.CharField(choices=[('FR', 'Français'), ('ANG', 'Anglais')], default='FR', help_text='language of course', max_length=3, verbose_name='course language')),
                ('category', models.CharField(choices=[('ANGL', 'Anglais'), ('FRAN', 'Français'), ('PHIL', 'Philosophie'), ('MATH', 'Mathématique'), ('CHIM', 'Chimie'), ('PHYS', 'Physique'), ('HIST', 'Histoire'), ('GEOG', 'Géographie')], default='FRAN', help_text='définir la catégorie qui représentent votre cours.', max_length=4, verbose_name='course category')),
                ('level', models.CharField(choices=[('6ième', '6ième'), ('5ième', '5ième'), ('4ième', '4ième'), ('3ième', '3ième'), ('2nde C', '2nde C'), ('2nde A', '2nde A'), ('1ère A', '1ère A'), ('1ère D', '1ère D'), ('1ère C', '1ère C'), ('Tle A', 'Tle A'), ('Tle D', 'Tle D'), ('Tle C', 'Tle C')], default='6ième', help_text='le niveau qui représentent votre cours.', max_length=6, verbose_name='course level')),
                ('description', models.TextField(blank=True, help_text='subject description. Who user learn ?', null=True, verbose_name='subject description')),
                ('resume', models.TextField(blank=True, help_text='subject resume.', null=True, verbose_name='subject resume')),
                ('image', models.ImageField(blank=True, help_text='upload subject cover', null=True, upload_to=utils.func_utils.upload_image_path, verbose_name='subject cover')),
                ('slug', models.SlugField(blank=True, help_text='link of subject', unique=True, verbose_name='link of subject')),
                ('free', models.BooleanField(default=False, help_text='this subject is free ?', verbose_name='subject is free ?')),
                ('published', models.BooleanField(default=False, help_text='this course is published ?', verbose_name='subject published ?')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_created', to='accounts.teacher', verbose_name='instructor')),
                ('students', models.ManyToManyField(blank=True, related_name='student_enrolled', to='accounts.Student', verbose_name='Student joined')),
            ],
            options={
                'verbose_name_plural': 'subject',
                'ordering': ['-created_at'],
                'get_latest_by': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='link of lesson', verbose_name='link of lesson')),
                ('title', models.CharField(help_text='add lesson title', max_length=200, verbose_name='lesson title')),
                ('chapter_desc', models.TextField(blank=True, help_text='add lesson description', null=True, verbose_name='lesson description')),
                ('order', utils.func_utils.CustomFields(blank=True, verbose_name='lesson number')),
                ('access', models.BooleanField(default=True, verbose_name='lesson is access ?')),
                ('movie', models.URLField(blank=True, help_text='add movies url', verbose_name='url movie')),
                ('document', models.FileField(blank=True, help_text='upload file', upload_to=utils.func_utils.save_chapiter_content_file, verbose_name='document')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='date created')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapiter', to='courses.course', verbose_name='course')),
            ],
            options={
                'verbose_name_plural': 'lessons',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='courses.subject', verbose_name='subject'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['id', 'uuid'], name='courses_sub_id_10b39e_idx'),
        ),
        migrations.AddIndex(
            model_name='coursechapter',
            index=models.Index(fields=['id'], name='courses_cou_id_b0cdb8_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['id', 'uuid'], name='courses_cou_id_da1218_idx'),
        ),
    ]
