# Generated by Django 4.2.2 on 2023-06-28 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="instructor",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="students",
        ),
    ]
