# Generated by Django 4.2.2 on 2023-06-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_remove_subject_instructor_remove_subject_students"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "get_latest_by": ["created_at", "update_at"],
                "ordering": ["order"],
                "verbose_name_plural": "cours",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={
                "get_latest_by": ["-created_at"],
                "ordering": ["-created_at"],
                "verbose_name_plural": "sujets",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="chapiter description",
                null=True,
                verbose_name="chapiter description",
            ),
        ),
    ]
