# This is a basic workflow that is manually triggered

name: Manuel workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
    pull_request:
      paths-ignore:
        - '**.md'
    schedule:
      - cron: "0 0* * 1-5"
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"

    - name: Set up python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install packages
      run: pipenv install

    - name: Test it
      run: make coverage

    - name: Check deploy configuration
      run: python manage.py check --deploy --fail-level WARNING
