name: Tests Runner

on: push

jobs:
	test:
  		runs-on: ubuntu-latest
  		steps:
  			- name: Get the code
  				uses: actions/checkout@v2
  				with:
  					fetch-depth: 1

  			- name: Cache python packages
  				uses: actions/cache@v1
  				with:
  					path: ~/.cache/pip
  					key: pip-${{ hashFiles('requirements.txt') }}

  			- name: Set up python
  				uses: actions/setup-python@v1
  				with: python-version: '3.x'
  				architecture: 'x64'

  			- name: Install packages
  				run: |
  					# Postgres dev headers for pg_config
  					# libpq-dev
  					# Graphviz support
  					# python3-dev graphviz libgraphviz-dev
  					sudo apt install libpq-dev python3-dev graphviz libgraphviz-dev
			
			- name: Install packages
				run: pip install -r requirements.txt

			- name: Test it
				run: make coverage

			- name: Check deploy configuration
				run: ./manage.py check --deploy --fail-level WARNING
